name: acbsecretshare
description: print out secrets via an encrypted debug message
branding:
  icon: "lock"
  color: "black"
author: alexcb
inputs:
  version:
    description: "version of secretshare to use."
    default: "latest"
  prerelease:
    description: "allow prerelease versions"
    default: "false"
  publickey:
    description: "public key to encrypt message with."
  msg:
    description: "message to display"
runs:
  using: node16
  main: dist/setup/index.js
  post: "dist/cache-save/index.js"
